### ISSUE TITLE
define how invalid `T` and/or `Abi` must be handled

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#12]
@jensmaurer:
> (22) datapar<T, Abi> should be specified to be an empty class with deleted constructors for incorrect T and Abi, or should that be an incomplete class?

Good question. I actually have put a `static_assert` for correct `T` in my implementation. But, you're right, this needs to be spelled out.

At this point I don't have implementation experience for either one. I guess for both choices I'd like to have a third template parameter (default initialized from `T` and `Abi`) that enables a specialization. IIRC this is a permitted addition in implementations of the standard, right?

**Comment by jensmaurer** [comment]
It seems LEWG/LWG currently favors "complete class type with deleted default constructor / deleted destructor / delete copy constructor / deleted copy assignment" for invalid T or Abi. This apparently is believed to help SFINAE in some cases, or so.

**Comment by mattkretz** [comment]
Yeah, SFINAE certainly would motivate me here, too. I'll add something and hope that it's implementable with reasonable effort. ;-)
