### ISSUE TITLE
Improve wording for binary_op in [datapar.reductions]

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#15]
@jensmaurer:
> (25) The definition of binary_op in reduce() should say something like "where both arguments..." The existing sentence is a bit obtuse.

**Comment by mattkretz** [comment]
e100b9f now says "Requires:  binary_op shall be  callable 2 with two  arguments of  type  T  or  two  arguments  of type datapar<T, A1>, where  A1 may be  different to Abi."

Good?

**Comment by jensmaurer** [comment]
What's the "2" doing there? Otherwise good.

**Comment by mattkretz** [comment]
Broken copy and paste from PDF. Alright.
