### ISSUE TITLE
generator constructor

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#18]
@jensmaurer:
> (28) As touched upon in Issaquah, a constructor taking a functor F is really useful

I have added this to the paper:

` template  <class G>  datapar(G  &&gen);`
*Remarks:*  This  constructor  shall not participate in overload resolution unless either `gen()` or `gen(declval<integral_constant<size_t,  0>>())` are well-formed with a return type of `value_type`.
*Effects:* Constructs an object where the i-th element  is  initialized to
• `gen()`, if `gen()` is well-formed,
• otherwise `gen(integral_constant<size_t, i>())`.
*Remarks:* The order of calls to gen is unspecified.

The `integral_constant` allows to the generator argument value to be used in constant expressions.

Having the order of calls undefined is maybe not really helpful. It basically enables explicit loop-vectorization, but I think we might rather want to rely on good old autovectorization here.

**Comment by jensmaurer** [comment]
I said "F", not "G". :-)

Hm.. Can I just use "[](int i) { return i; }" to get a 0...n-1 datapar with this kind of declaration?
Having `gen()` work seems not particularly helpful; dropping an argument value is always possible, and writing a lambda is a short + concise way of doing that if you must call a gen() function.
And I'm not seeing the need for integral_constant to make this workable in constant expressions, as long as gen() ist constexpr. However, it does allow template magic at that point, right.

**Comment by mattkretz** [comment]
> Can I just use "[](int i) { return i; }" to get a 0...n-1 datapar with this kind of declaration?

Yes, except that this'll only work for `datapar<int>` because the return type must match the `value_type` exactly.

> dropping an argument value is always possible

fair enough. Will drop the no-arg case.

> I'm not seeing the need for integral_constant to make this workable in constant expressions, as long as gen() ist constexpr.

Function arguments are never constexpr, even if the function itself is constexpr. (which I think is quite sad). With a generic lambda you can capture the `integral_constant` and with the implicit conversion operator this just works.

**Comment by mattkretz** [comment]
Any opinion on "The order of calls to gen is unspecified."?

**Comment by jensmaurer** [comment]
No objection to unspecified order.
