### ISSUE TITLE
mention cv-unqualified restriction for T

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#19]
@jensmaurer:
> (31) Do we say somewhere that for datapar<T>, T must be a cv-unqualified integral or floating-point type?

4.1.2.1 p2: "The first template argument `T` must be an integral or floating-point fundamental type. The type `bool` is not allowed."
Same for `mask` in 4.1.4.1 p2.

If I need to mention cv-unqualified, do I have to mention not reference and/or not pointer, too?

**Comment by jensmaurer** [comment]
It's an open core question whether "const int" is an integral type. I guess it rather should be. No, pointers and references are different; "int *" or "int&" is expressly not an integer.

Just say "The first template argument T must be a cv-unqualified integral or floating-point type (3.9.1 [basic.fundamental])." and all is well.
