### ISSUE TITLE
reconsider `bool` return type of `mask` compares

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#2]
> My motivation for returning bool on mask compares is the use-cases I encountered. Whereas I have few uses for an implicit all_of reduction on datapar compares, this is different for masks. Whereas I have no alternative operator for element-wise datapar compares, this is different for masks where I can use xor.

Hm... == returning bool on masks, but still having || on masks returning a mask is ... slightly odd.  The rule with the datapar stuff used to be "all operators apply element-wise".  Having an exception here is odd.

The general problem with the mask reduction is that there are three choices: all_of, any_of, none_of that need to be mapped to a bool that has just two possible values.  There is no obviously "right" answer, so we need user input.
```
  if (all_of(...))
```
or
```
  if (any_of(...))
```
doesn't sound too wrong, and makes the reduction explicit.

> And finally, all_of(mask == mask) must be implemented with a less efficient intrinsics sequence than an operator== that returns bool.

Let's talk specifics here.

On Intel SSE2, "mask == mask" as a vector is "pxor" followed by "not" (must be constructed via "xor 0xff..ff");
"all_of" is "pmovmsk" followed by a scalar compare with 0xffff or "ptest x, 0xff...ff" and the result is in the carry flag (when you have SSE4_1).

For == returning bool, it seems you could do "pxor" then "ptest x,x" (when you have SSE4_1) and the result is in the zero flag.

Sounds like a compiler optimization opportunity to track the value from the SSE mask to the scalar register and/or the flags. I can't find anything in current gcc that would attempt to understand what a ptest intrinsic does, or a pmovmsk.

> However, the consistency argument is strong here. I might be convinced to change this. But not before the paper deadline.

Agreed on the last part.  Please add an open issue item for the "mask==mask returns scalar bool, not mask" issue.

**Comment by mattkretz** [comment]
@jensmaurer 
> Let's talk specifics here.

See https://godbolt.org/g/9gzZJW. If you switch to Clang, you see that it isn't much different. You're certainly right about the compiler, that it should, in theory, optimize the `all_of(cmpeq_mask)` to `cmpeq1`.

I'll be happy to change the return type if you give me the go on this.

**Comment by jensmaurer** [comment]
Yes, I'd say for consistency, mask==mask should return a mask, not a scalar.
