### ISSUE TITLE
Should abs(datapar<signed>) return datapar<unsigned> to be non-narrowing?

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#20]
@jensmaurer:
> (30) Should abs(datapar<signed>) return datapar<unsigned> to be non-narrowing?

Ouch, just for the one `numeric_limits<signed>::min()` case? Convert to something that does not implicitly convert back to the type passed to `abs`? If we had implicit conversions between `signed` and `unsigned` I'd say yes, why not? But with the heavily restricted conversions, this feels like saying "hey did you notice `abs(integral)` has a corner case? No, well I'll make you think about it from now on..." ;-)

I'm very much in favor of sticking to the precedent of the scalar interface here.

**Comment by jensmaurer** [comment]
Ok, fine with me.
