### ISSUE TITLE
Talk about noexcept?

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#31]
@jensmaurer: Should the wording talk about noexcept? AFAICS all `datapar` and `mask` functions should be `noexcept`. But do we want to / have to mandate this in the wording?

**Comment by jensmaurer** [comment]
The LWG approach to "noexcept" is that all functions with a wide contract (i.e. no restrictions on the argument types) get a "noexcept", anything else that doesn't throw gets a "Throws: Nothing." clause. And yes, it seems that needs to be said in the function declarations / descriptions. It seems most functions will be "noexcept".

**Comment by mattkretz** [comment]
I'll add noexcept to all functions except `datapar(generator)` and `where_expression::operator@=(U &&)`.

* The generator ctor calls the generator function and thus depends on the noexcept'ness of the generator. This could be done with a conditional noexcept, but I don't think it's worth specifying, and it's going to be horrible because the generator is called with `integral_constant` and thus can potentially call different overloads for every index.
* The `where_expression` (compound) assignment operators forward their argument `U &&x` in the implementation. Thus a conversion operator of `U` may be called and might throw. Again, could be conditional noexcept, but do we care enough?

**Comment by mattkretz** [comment]
I'm not comfortable with this change, I don't have enough experience with adding `noexcept` vs. saying "Throws: nothing" and saying nothing at all. Should we rather wait for LWG guidance on this? It's easy enough to change...

**Comment by jensmaurer** [comment]
Ok, let's ignore noexcept for now.

**Comment by mattkretz** [comment]
A data point: Pending the results from the reflection efforts, I'd like to extend `datapar<T>` to work for user-defined types `T`, by wrapping member types recursively in `datapar` (with some smart logic in choosing the right ABI type). At that point the `noexcept` case isn't so obvious anymore.

**Comment by geoffromer** [comment]
LWG generally prefers to avoid conditional `noexcept`, except for move and swap operations. Those always use `noexcept` because they never have preconditions. For other operations, you can just say something like "Throws: any exception thrown by T's move constructor.".

**Comment by jensmaurer** [comment]
@geoffromer: Agreed.
