### ISSUE TITLE
masked load ctor

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#32]
@jensmaurer 
Both `datapar` and `mask` have a load ctor overload that takes a `mask` argument. This allows us to write:
```cpp
const datapar<int> v(mem, mask, flags::vector_aligned);
// the alternative cannot be const:
datapar<int> w{};  // zero
where(mask, w).memload(mem, flags::vector_aligned);
```

The masked load and store functions are gone - moved to `where_expression`. Any idea what I should do with the masked load ctor? Keep. Burn. Ask LEWG?

**Comment by jensmaurer** [comment]
That's what I meant when talking about the masked load/stores not really fitting into the where_expression: The constructors don't really fit. And yes, the "const" datapar is important here. What could we do otherwise?

```
const datapar<int> v = memload(mem, mask, flags) // ???
const datapar<int> v = where(mask).memload(mem, flags) // yet another where_expression
const datapar<int> v = where(mask)(mem, flags) // yet another where_expression
```

Keep the masked load in the constructors as-is.

Btw, did you add a statement somewhere that the memload/memstore format of "mask" is "array of size() bool"?

**Comment by mattkretz** [comment]
All of your ideas require some kind of `load_expression` temporary to enable converting loads. I.e. if the `int` `datapar::value_type` cannot be inferred from the type of `mem`.

Other ideas:
```cpp
const datapar<int> v(where(mask, mem), flags);  // inconsistent: no v.memload(where(mask, mem), flags)
const datapar<int> w = where(mask, datapar<int>()).memload(mem, flags);  // dangerous, consider:
where(mask, w).memload(mem, flags);  // v is const, this is a no-op. [[nodiscard]] can help
```

I like the const memload overload best. It seems most consistent and enables different values for the masked parts (besides 0). Close relative:
```cpp
const datapar<int> w = mask ? datapar<int>(mem, flags) : datapar<int>();
```
(Note that the load is a full vector load now, though. The real masked memload avoids an out-of-bounds access via: "*Remarks: If M is not bool and if the largest i where `mask[i]` is `true` is greater than the number of values pointed to by `mem`, the behavior is undefined.*"

> Btw, did you add a statement somewhere that the memload/memstore format of "mask" is "array of size() bool"?

It's always been there, because `mask::value_type` is `bool` and:
```cpp
template <class Flags> void memload(const value_type *, Flags);
template <class Flags> void memstore(value_type *, Flags);
```
The matching `size()` is part of a remark: "*Remarks: If `size()` returns a value greater than the number of values pointed to by the first argument, the behavior is undefined.*"

**Comment by jensmaurer** [comment]
It would be good to convert the "Remarks" talking about "undefined behavior" into "Requires", for example "Requires: `size()` is less than or equal to the number of values pointed to by `p`." (yes, give the pointer a name) This makes the "undefined behavior" less visible :-)

"I like the const memload overload best." I assume you're talking about
`datapar x = where(mask, w).memload(mem, flags);`

Does that mean you want to remove the constructor taking a pointer?

**Comment by mattkretz** [comment]
> It would be good to convert the "Remarks" talking about "undefined behavior" into "Requires", for example "Requires: size() is less than or equal to the number of values pointed to by p." (yes, give the pointer a name) This makes the "undefined behavior" less visible :-)

Should be clearer for implementers, even. Thanks.

> "I like the const memload overload best." I assume you're talking about `datapar x = where(mask, w).memload(mem, flags);`

Yes.

> Does that mean you want to remove the constructor taking a pointer?

I'd remove the masked load ctor. I'd keep the load ctor (just as `datapar::memload(U *, Flags)` still exists.

**Comment by jensmaurer** [comment]
I'm slightly afraid of the user-side syntax overhead to provide a "w" in that case (even if it's just datapar<int>()). But ok, let's go there; this moves all masking into where(), which is very nice + consistent.

(Turns out that Intel x86 doesn't have a masked load, just a masked store.)

**Comment by mattkretz** [comment]
Yes, it might be nice to be able to say `v = where(mask, {}).memload(mem, flags);` or `v = where(mask, 0).memload(mem, flags);` and infer the `datapar` template arguments from the `mask` type. I'll see how feasible this is.

Intel has masked loads starting with AVX:
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=512_mask_load&expand=3077
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=maskload&expand=3280

**Comment by jensmaurer** [comment]
I'm sorry, this page is extremely slow for my very old machine and old-ish browser. What's the actual hardware instruction you're talking about?

For where(mask, x), we usually want to deduce the template arguments for where_expression from x let mask be a non-deduced context. That approach then fails for where(mask, 0).

**Comment by mattkretz** [comment]
Instructions are v(p)maskmov* for AVX(2) and vmov* with write-mask argument for AVX512.

Yes, the `where(datapar<T, A>::mask_type, datapar<T, A>)` signature must stay. I'm looking into a feasible option for an overload. The obvious `where(mask<T, A>, mas<T, A>::datapar_type)` overload would require another `where(mask<T, A>, datapar<T, A>)` for disambiguation (though I'm not 100% I'm overlooking something).
But depending on how we resolve #34 there may be more/easier options.
