### ISSUE TITLE
preconditions of special math functions & error handling

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#35]
@jensmaurer 
The current wording for datapar math functions is hand-wavy:
> Each listed function concurrently applies the indicated mathematical function component-wise.
The results per component are not required to be binary equal to the application of the function which is overloaded for the element type.

It ignores to talk about preconditions (input in range of the function) and results on violation of those preconditions (`asin(datapar<float>(-2.f))` just doesn't make much sense, but will it set `errno` if we don't improve the wording?).
We certainly want to never set `errno`. Do we want exceptions on precondition violation, or UB, or some datapar<optional<T>> return type? I.e. a mask + datapar.

I don't recall any wishes of SG1 on this. I'd favor UB at this point, to enable the most efficient implementation.

**Comment by jensmaurer** [comment]
Since the component-wise evaluation yields undefined behavior (since a library precondition is violated), so does the datapar evaluation if any conmponent has a bad value. Thus, just add a note that says that.

**Comment by mattkretz** [comment]
Hmm, "implementation-defined" might be a more user-friendly option here, no? But this really depends on the output of the larger discussion on this topic.
