### ISSUE TITLE
reference <op> reference is ambiguous

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#36]
@jensmaurer, @brycelelbach
```cpp
datapar<int> x = ...;
x[0] + x[0];  // ambiguous!
```
That's because x[0] is directly convertible to `datapar<int>` via the broadcast constructor. Thus, the builtin `int + int` operator (after conversion via `reference::operator value_type() const` is equally viable as `friend datapar operator+(const datapar &, const datapar &)` (at least GCC and ICC say so). Removing the broadcast ctor would make me unhappy:
```cpp
x + x[0];  // implicit broadcast of the RHS; would be ill-formed
```

The alternative resolution requires overloads of the binary operators of the `reference` type. I'll add this resolution to the paper (and implemented the solution in my implementation). If you see a problem with this, please speak up.

**Comment by jensmaurer** [comment]
The two user-defined conversion choices are what, here?
"`datapar<T>::reference` converts to T" and "`datapar<T>` constructor taking a `datapar<T>::reference`"?

**Comment by mattkretz** [comment]
Yes. The `datapar` broadcast ctor looks like this currently:
![grafik](https://cloud.githubusercontent.com/assets/3306474/23365547/c25bfb48-fd03-11e6-976c-ee50e1da86bd.png)
Thus it can directly convert from `datapar::reference`, which is implicitly convertible to `value_type` via its `operator value_type() const`.

Note that I modified the signature to `datapar(U &&)` in my implementation to resolve #30.
