### ISSUE TITLE
reduce math overloads

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#4]
> (17) I totally hate showing five overloads for sin/cos/etc.  At the
> very least, I'm opposed to having "...f" and "...l" suffix overloads;
> they're ancient history from C even they don't need anymore given
> <tgmath.h>, if I understand correctly.

Ack.

The main argument for having f and l suffix versions would be code that was written for scalar types and now just works with datapar as well.

That said. Vc doesn't have those functions. I'm happy to let them go. This was guidance from SG1 - though we didn't talk about the f and l suffix versions explicitly (IIRC).

To reduce the remaining three overloads to one, the signature would need to be:
template <class T, class A> datapar<T, A> sin(datapar<T, A>)

I'd like T to be restricted to float, double, long double. I.e. requires clause then?

**Comment by jensmaurer** [comment]
Having three overloads is fine for me, it's not much different from having enable_if machinery, and a lot more explicit.
