### ISSUE TITLE
widen cast/function

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#46]
@jensmaurer For the `widen` function we have several possibilities:
```cpp
using floatv = datapar<float>;
using doublev = fixed_size_datapar<double, floatv::size()>;

auto f(floatv x, doublev y) {
  return widen(x) * y;  // widen returns a wrapped floatv indicating that non-narrowing
                        // implicit conversions are allowed
  return widen<double>(x) * y;  // the destination Abi type is implicit and probably
                                // always fixed_size (could also be defaulted second
                                // template parameter)
  return widen<doublev>(x) * y;  // the destination Abi type is explicit
}
```

Which one did you have in mind? In terms of naming, the latter two should probably be called `widen_datapar_cast`? The first `allow_widen`?

**Comment by mattkretz** [comment]
@jensmaurer If you have an opinion on this function, please let me know ASAP.

**Comment by mattkretz** [comment]
![image](https://user-images.githubusercontent.com/3306474/27134291-6855f070-5115-11e7-8b10-3200e92e8237.png)
Any idea for the name? We already have `static_datapar_cast`, which allows any element type conversion (for equal `size()`). This function would just be the "safe subset".

**Comment by mattkretz** [comment]
Oh, I should add that the cast functions work slightly different:
```cpp
native_datapar<float> v;
auto w0 = static_datapar_cast<double>(v);
auto w1 = datapar_cast<fixed_size_datapar<double, v.size()>>(v);
```
That's easy to change (either way). In any case, I don't think it's useful to have them be different.

**Comment by jensmaurer** [comment]
I had this in mind: `return widen<double>(x) * y;  `

However, I didn't get around to trying it out, so I'm fine to progress the paper in Toronto without "widen".

**Comment by mattkretz** [comment]
On Freitag, 16. Juni 2017 18:24:56 CEST Jens Maurer wrote:
> I had this in mind: `return widen<double>(x) * y;  `

Right. I hesitated to do that because it requires another proxy/magic type. 
I'll see what I can propose until Toronto. However, it might be best to 
postpone the "widen" feature to a new paper, I think.

> However, I didn't get around to trying it out, so I'm fine to progress the
> paper in Toronto without "widen".

right. It should have at least an answer to the request from Kona, though.

**Comment by jensmaurer** [comment]
"I hesitated to do that because it requires another proxy/magic type."

Why?  `widen<T>(datapar<T2, Abi>)` should return `datapar<T, fixed_size<whatever>>`, right?

**Comment by mattkretz** [comment]
Hmm, true. `fixed_size` implicitly converts to other ABIs as long as the size fits. I was thinking about `return widen(x) * y`. But aren't you asking for the exact same function as `static_datapar_cast` then?

**Comment by mattkretz** [comment]
Ah no, of course. It's `static_datapar_cast` + the restriction on value-preserving element type conversion. So what I specified above, but change the first template parameter to an element type instead of a datapar type.
