### ISSUE TITLE
integrate masked load/store with where

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#5]
> (18) I'd really like to see masked load/store somehow integrated with
> "where", but I can't come up with useful syntax.  In particular, the
> mask more prevalently applies to the memory location/s written/read
> than the datapar.  (A store leaves non-chosen locations untouched.)

where(mask, x).copy_from(mem)
where(mask, x).copy_to(mem)

What do you think?

**Comment by jensmaurer** [comment]
For copy_from(mem), that's probably fine, but for copy_to(mem), the central point is that certain memory locations are not written; not that certain parts of the source remain untouched.

But maybe that just needs to grow on me... Yeah, this seems to be fine. (Note: Needs _where_expr for "const datapar&" for x.)

**Comment by mattkretz** [comment]
(I have the `const datapar &` overload for `where` for reductions already.)

Consider the options for interpreting the prose of `where(mask, x).memstore(mem)`:

* "Where `mask` is true take `x` and store it to `mem`"
* "Where `mask` is true store `x` to `mem`"
* "Where `mask` is true store `x` to `mem`, where `mask` is false write *something* to `mem`"

I think the third one is odd. I think the `where` syntax is a lot clearer than `x.memstore(mem, mask)`.

I'll put on my backlog then.

**Comment by jensmaurer** [comment]
Agreed. The syntax works, and is a lot clearer than the member function. This looks now very nice and consistent, we need to teach people simply "use `where(mask, x).operation` instead of `x.operation` if you want masked behavior for the operation". Cool, and maps nicely to AVX512 (where every operation is potentially masked).

**Comment by mattkretz** [comment]
Note that I have to add two more `where` overloads so that I can get masked load/store on masks. This automatically also adds masked binary operators on masks.

**Comment by mattkretz** [comment]
depends on #23
