### ISSUE TITLE
should mask follow bitset?

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#50]
@jensmaurer:
I just realized that `std::bitset` has the member functions `all`, `any`, `none`, and `count` which `mask` provides as non-member functions `all_of`, `any_of`, `none_of`, and `popcount`. I think `std::bitset` should have used the `mask` approach... But, should this influence the `datapar`/`mask` design? I guess the paper should at least mention this? Any opinion?

See e.g. http://en.cppreference.com/w/cpp/utility/bitset

**Comment by jensmaurer** [comment]
"I think std::bitset should have used the mask approach."

Agreed. all_of, any_of, none_of are names of algorithms in [alg.nonmodifying], and having them as non-member functions feels "right".

If someone desperately wants none/any/all member functions in datapar's mask, we can add them (as a redundant thing).

Suggestion: Add a section "naming" (you should already have one for the datapar naming, and have a subsection "mask queries" or so, and show the two options, with preference to the current one.

**Comment by mattkretz** [comment]
![grafik](https://user-images.githubusercontent.com/3306474/27129703-7bb3e832-5103-11e7-9fcb-cf7cf56c9493.png)

**Comment by jensmaurer** [comment]
Also, the "bit iterators" paper uses the free functions (algorithms) for bit sequences.
