### ISSUE TITLE
load/store naming

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#6]
> (19) I see the argument on the load/store naming vs. atomic<>,
> but the alternatives are worse.  Who objected to load/store?
> Maybe memload / memstore to make the direction extra-clear?

I mentioned the atomic interface in SG1 and an LEWG small group. Especially the latter recommended to find a different name.

I agree that having load/store in the name makes it much more discoverable for people with existing SIMD knowledge.

**Comment by jensmaurer** [comment]
I'd suggest memload and memstore; this is what those functions do: load from memory and store to memory.

**Comment by mattkretz** [comment]
I'm happy with your suggestion. There was not much further input from WG21 on this issue, so let's just do this.
